CREATE TABLE IF NOT EXISTS CART(
    id INTEGER AUTO_INCREMENT NOT NULL,
    product_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    desired_quantity INTEGER NOT NULL DEFAULT 0,
    unit_price DECIMAL(8,2) DEFAULT 0.00,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHECK(unit_price >= 0),
    CHECK(desired_quantity >= 0),
    PRIMARY KEY(id)
);

ALTER TABLE CART
ADD CONSTRAINT FK_Cart_ProdId
FOREIGN KEY(product_id) REFERENCES PRODUCTS(id);

ALTER TABLE CART
ADD CONSTRAINT FK_Cart_UserId
FOREIGN KEY(user_id) REFERENCES USERS(id);

ALTER TABLE CART
ADD UNIQUE UniqueCartComposite(product_id, user_id);