CREATE TABLE Ratings(
    id INTEGER NOT NULL AUTO_INCREMENT,
    product_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    rating INTEGER NOT NULL DEFAULT 0,
    comment TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CHECK (rating >= 0 AND rating <= 5)
);

ALTER TABLE Ratings
ADD CONSTRAINT FK_product_id 
FOREIGN KEY (product_id) REFERENCES Products(id);

ALTER TABLE Ratings
ADD CONSTRAINT FK_user_id
FOREIGN KEY (user_id) REFERENCES Users(id);